"""Add password reset tokens table

Revision ID: d43f9fa0c6d1
Revises: b4ac7e351453
Create Date: 2026-08-28 18:56:29.530077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd43f9fa0c6d1'
down_revision: Union[str, Sequence[str], None] = 'b4ac7e351453'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
