"""add expires_at to password reset tokens

Revision ID: dbf6437050e2
Revises: d43f9fa0c6d1
Create Date: 2026-08-28 20:24:56.686167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbf6437050e2'
down_revision: Union[str, Sequence[str], None] = 'd43f9fa0c6d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_reset_tokens', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('password_reset_tokens', 'expires_at')
    # ### end Alembic commands ###
